services:
  prl-vts3a:
    container_name: prl-vts3a
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3123:3123"
    restart: "unless-stopped"
    environment:
      - PYTHONUNBUFFERED=1
      