FROM python:3.13.2-slim-bookworm

ENV ENV production
ENV TMPDIR=/tmp
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN mkdir -p /app && chmod -R 777 /app && mkdir -p /tmp && chmod -R 777 /tmp

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:3123", "main:app"]
